name: deploy-to-gcp

on:
  push:
    branches: [prod]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: carpool-service-ui
  REGION: asia-east1
  python-version: '3.9'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/auth@v1
        id: auth
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true

      - name: Build Docker Image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/carpool-service-ui/${{ env.SERVICE }}:01 .
          gcloud auth configure-docker asia-east1-docker.pkg.dev
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/carpool-service-ui/${{ env.SERVICE }}:01

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/carpool-service-ui/${{ env.SERVICE }}:01

      - name: Use output
        run: curl "${{ steps.deploy.outputs.url }}"

      - name: Info
        run: gcloud info

