name: unit-test

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: carpool-service-backend-unitest
  REGION: asia-east1

jobs:
  e2e-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: build test docker
        run:
          docker build -t unit_test:01 .

      - name: run test docker
        run:
          docker run -d -p 3000:3000 unit_test:01

      - name: sleep
        run:
          sleep 10

      - uses: google-github-actions/auth@v1
        id: auth
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true

      - name: Build Docker Image
        run: |
          gcloud auth configure-docker asia-east1-docker.pkg.dev
          docker pull ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/carpool-service-backend-unitest/${{ env.SERVICE }}:01
          docker run -d -p 3000:3000 ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/carpool-service-backend-unitest/${{ env.SERVICE }}:01

      - name: Install Chrome
        run: |
          apt-get update
          apt-get install -y google-chrome-stable

      - name: Download ChromeDriver
        run: |
          LATEST_CHROMEDRIVER=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          curl -o chromedriver.zip https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER/chromedriver_linux64.zip
          unzip chromedriver.zip
          chmod +x chromedriver

      - name: run test
        run: |
          python e2e_test.py

