name: e2e-test

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: carpool-service-backend-unitest
  REGION: asia-east1

jobs:
  e2e-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: build test docker
        run:
          docker build -t unit_test:01 .

      - name: run test docker
        run:
          docker run -d -p 3000:3000 unit_test:01

      - uses: google-github-actions/auth@v1
        id: auth
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true

      - name: Pull Backend Docker Image
        run: |
          gcloud auth configure-docker asia-east1-docker.pkg.dev
          docker pull ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/carpool-service-backend-unitest/${{ env.SERVICE }}:01
        
      - name: RUN Backend Docker Image
        run: | 
          docker run -d -p 8080:8080 ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/carpool-service-backend-unitest/${{ env.SERVICE }}:01

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Download ChromeDriver
        run: |
          curl -o chromedriver.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/120.0.6099.71/linux64/chromedriver-linux64.zip
          unzip chromedriver.zip
          sudo chmod +x chromedriver-linux64/chromedriver

      - name: install selenium
        run: |
          pip3 install selenium

      - name: run test
        run: |
          python e2e_test.py

